name: Publish to another (Prod) repository

#on:
#  pull_request:
#    types:
#      - closed
#
#jobs:
#  if_merged:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#    - run: |
#        echo The PR was merged
#

on:
  push:
# Pattern matched against refs/tags
    tags:        
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output directory
        run:  mkdir output   # some command from your repository that creates
      - name: use rsync to selectively copy files
        run:  rsync -a --exclude '.git' --exclude 'output' . output # output to "source-directory" ("output" in the example)
      - name: show the repo files now    
        run:  ls -la output
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: 'HunterGerlach'
          destination-repository-name: 'multi-stage-deployment-example-nextjs-github-pages-production'
          user-email: hunter@huntergerlach.com
          target-branch: main

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           repository: HunterGerlach/nextjs-github-pages-multi-envs-prod
#           path: ./
#           token: ${{ secrets.REPO_TOKEN }}

#       - uses: actions/upload-artifact@v2
#         with:
#           name: root
#           path: ./
#           token: ${{ secrets.REPO_TOKEN }}
